"""Executive summary — a concise, scannable read of the dashboard, generated by
TEMPLATED RULES (no LLM, zero token cost). Turns the headline signals into 3-6
plain-English takeaways for a quick understanding of the economy, market, and
cycle position."""
from __future__ import annotations

import config


def _isnum(x) -> bool:
    try:
        return x == x and x is not None
    except Exception:
        return False


def executive_summary(facts: dict) -> list[str]:
    """facts: regime_label, regime_score, cycle_phase, cycle_note, vix, cape,
    curve_inverted, sahm_triggered, credit_widening, top_mover (name, chg)."""
    out = []

    rs = facts.get("regime_score")
    rl = facts.get("regime_label")
    if rl and _isnum(rs):
        tilt = ("a risk-on tilt" if rs > 0.1 else
                "a risk-off tilt" if rs < -0.1 else "a balanced stance")
        out.append(f"**Market regime: {rl}** ({rs:+.2f}) — the weighted blend of rates, "
                   f"credit, volatility, trend and valuation points to {tilt}.")

    cp = facts.get("cycle_phase")
    if cp:
        note = facts.get("cycle_note") or ""
        out.append(f"**Business cycle: {cp}.** {note}".strip())

    flags = []
    if facts.get("curve_inverted"):
        flags.append("the yield curve is inverted (a classic recession lead)")
    if facts.get("sahm_triggered"):
        flags.append("the Sahm rule has triggered")
    if facts.get("credit_widening"):
        flags.append("credit spreads are widening")
    if flags:
        out.append("⚠️ **Watch:** " + "; ".join(flags) + ".")

    cape = facts.get("cape")
    if _isnum(cape):
        state = ("rich" if cape >= config.CAPE_EXPENSIVE else
                 "cheap" if cape <= config.CAPE_CHEAP else "fair")
        out.append(f"Valuations look **{state}** (Shiller CAPE {cape:.0f}), which historically "
                   f"shapes longer-horizon returns more than near-term direction.")

    vix = facts.get("vix")
    if _isnum(vix):
        vstate = ("elevated" if vix >= config.VIX_PANIC else
                  "calm" if vix <= config.VIX_CALM else "moderate")
        out.append(f"Volatility is **{vstate}** (VIX {vix:.0f}).")

    tm = facts.get("top_mover")
    if tm and _isnum(tm[1]):
        direction = "up" if tm[1] >= 0 else "down"
        out.append(f"Biggest cross-asset move today: **{tm[0]} {direction} {abs(tm[1]):.1f}%**.")

    return out or ["Live signals are unavailable right now — see the source status below."]
